module.exports = {
  general:{
    src:[
      'bower_components/jquery/dist/jquery.min.js',
      'bower_components/angular/angular.js',
      'bower_components/angular-animate/angular-animate.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/angular-ui-router/release/angular-ui-router.js',
      'bower_components/angular-ui-utils/ui-utils.js',
      'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'bower_components/oclazyload/dist/ocLazyLoad.js',
      'bower_components/angular-loading-bar/build/loading-bar.min.js',
      'bower_components/perfect-scrollbar/min/perfect-scrollbar.min.js',
      'bower_components/angular-perfect-scrollbar/src/angular-perfect-scrollbar.js',
      'bower_components/angular-inview/angular-inview.js',
      'app/js/app.js',
      'app/js/app.config.js',
      'app/js/app.lazyload.js',
      'app/js/app.router.js',
      'app/js/app.main.style4.js',
      'app/js/services/ui-load.js',
      'app/js/filters/moment-fromNow.js',
      'app/js/directives/nganimate.js',
      'app/js/directives/ui-jq.js',
      'app/js/directives/ui-module.js',
      'app/js/directives/ui-nav.js',
      'app/js/directives/ui-bootstrap.js',
      'app/js/directives/ui-chatwindow.js',
      'app/js/directives/ui-sectionbox.js',
      'app/js/controllers/bootstrap.js',
      'app/js/controllers/topbar.js',
      'app/js/controllers/chat.js',
      'bower_components/Chart.js/Chart.min.js'
    ],
    dest:'angular/js/app.src.js'
  }
}
